config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end

  # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :users do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 200 }
  validates_numericality_of :posts_counter, only_integer: true, greater_than_or_equal: 0

  def recent_three_posts
    posts.last(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def index
    users = User.all
    render json: users, status: :ok
  end

  def show
    user = User.find(params[:id])
    render json: user, status: :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_three_posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Listing all the Users <h1>

<div class="body">
    <% @users.each do |user| %>
        <div class="user_wrapper">
         <%= link_to user do %>
            <div class="user_info">
            <div class="img_container">
            <% if user.photo.nil? %>
            <%= image_tag "https://bit.ly/3WU8Zoi", class:"user_image"%>
          <% else %>
          <%= image_tag user.photo, class:"user_image" %>
          <% end %>
                
            </div>

            <div class="user_post">
                <div class="user_name">
                    Username: <%= user.name %>
                </div>
                <div class="post_count">
                Number of posts: <%= user.posts_counter %>
                </div>
            </div>
            </div>
            <% end %>
        </div>
    <% end %>

</div>

app/views/users/show.html.erb
<h1>Listing all the Posts <h1>

<div class="body">
<%= link_to new_user_post_path(@user), class: "link" do %>
    <button type="button" class="see-all-posts-button">Create new post</button>
<% end %>
        <div class="user_info">
            <div class="img_container">
            <% if @user.photo.nil? %>
            <%= image_tag "https://bit.ly/3WU8Zoi", class:"user_image"%>
          <% else %>
          <%= image_tag @user.photo, class:"user_image" %>
          <% end %>
            </div>
            <div class="user_post">
                <div class="user_name">
                    Username: <%= @user.name %>
                </div>
                <div class="post_count">
                Number of posts: <%= @user.posts_counter %>
                </div>
            </div>
        </div>

        <div class="user_bio">
         <p>Bio</p>
         <p><%= @user.bio %></p>
        
        </div>

        <div class="posts_container">

            <% @posts.each_with_index do |post, index| %>
                <div class="posts_wrapper">
                    <div class="post_wrapper">
                    <p class="post_number">post: <%= post.id %></p>
                    <p class="post_number"><%= post.title %></p>
                    <p class="post_number"><%= post.text %></p>
                    <div class='comments_likes'>
                        <span>comments: <%= post.comments_counter %></span>
                        <span>likes: <%= post.likes_counter %></span>
                    </div>
                    </div>
                <div>
            <% end %>
        </div>

        <%= link_to user_posts_path(@user) do %>
            <button type="button" class="see-all-posts">See all posts</button>
        <% end %>
</div>