config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create destroy] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end

  # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :users do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = Post.where(author_id: user.id).includes(:comments)
    render json: posts, status: :ok
  end

  def show
    user = User.find(params[:id])
    posts = user.recent_three_posts
    render json: posts, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id).includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
    @user = @post.author
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404.html', status: :not_found
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Deleted!' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>Posts for selected user</h1>

<div class="body">
        <div class="user_info">
            <div class="img_container">
            <% if @user.photo.nil? %>
            <%= image_tag "https://bit.ly/3WU8Zoi", class:"user_image"%>
          <% else %>
                <%= image_tag @user.photo, class:"user_image" %>
                <% end %>
            </div>
            <div class="user_post">
                <div class="user_name">
                    Username: <%= @user.name %>
                </div>
                <div class="post_count">
                Number of posts: <%= @user.posts_counter %>
                </div>
            </div>
        </div>

        <div class="user_bio">
        <p>Bio</p>
        <p><%= @user.bio %></p>
       
       </div>

        <div class="post_container">
            <% @posts.each_with_index do |post, index| %>
                <div class="post_comment_wrapper">
                    <%= link_to user_post_path(@user, post) do %>
                    <div class="posts_wrapper">
                        <p class="post_number">post<%= post.id %></p>
                        <p class="post_number"><%= post.title %></p>
                        <div>
                            <span>comments: <%= post.comments_counter %></span>
                            <span>likes: <%= post.likes_counter %></span>
                        </div>
                    </div>
                    <% end %>
                    <% if can? :destroy, post %>
            <%= form_with model: post, url: user_post_path(@user, post), method: :delete do |form| %>
              <%= form.submit "Delete Post", class: "delete-button" %>
            <% end %>
          <% end %>
                <div class="comment">
                    <% post.recent_five_comments.each do |comment| %>

                        <div class="user_comment">
                            <span class="comment_text"><%= @user.name %>: </span>
                            <span class="comment_text"><%= comment.text %></span>
                        </div>
                    <% end %>
                </div>
            </div>
            <% end %>
        </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="new-post-title">Create a New Post</h2>

  <%= form_with model: @post, url: user_posts_path, class: 'post-form' do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>
      <%= form.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>All comments for the post</h1>

<div class="post_user_wrapper">
    <span>post <%= @post.id %> by: </span>
    <span>post <%= @user.name %></span>
    <p><%= @post.title %></p>
    <div class="likes_comments_post">
        <span>Comments counter: <%= @post.comments_counter %>,</span>
        <span>Likes_counter: <%= @post.likes_counter %></span>
    </div> 
    <div class='add_like_wrapper'>
        <%= render "likes/like" %>
    </div>
</div>
<% if can? :destroy, @post %>
            <%= form_with model: @post, url: user_post_path(@user, @post), method: :delete do |form| %>
              <%= form.submit "Delete Post", class: "delete-button" %>
            <% end %>
          <% end %>

<div class="post_comments_wrapper">
    <% @comments.includes(:author).each do |comment| %>
            <div class="post_comments">
                <span><%= comment.author.name %>: </span>
                <span><%= comment.text %></span>
            <div> 
            <% if can? :destroy, comment %>
<%= form_with model: comment, url: user_post_comment_path(@user, @post, comment), method: :delete do |form| %>
  <%= form.submit "Delete", class: "delete-button" %>
<% end %>
<% end %> 
    <% end %>
 <div>

<div class='add_comment_wrapper'>
 <%= render "comments/form" %>
</div>